VeriSilicon/tflite-vx-delegate

CMakeLists.txt, README.md, cmake/tflite.cmake
=> Support cmake build

CMakeLists.txt, README.md, examples/minimal/BUILD, examples/minimal/CMakeLists.txt, examples/minimal/README.md, examples/minimal/minimal.cc, examples/python/label_image.py
=> Add modified python/c++ demo

CMakeLists.txt, cmake/tflite.cmake, examples/minimal/minimal.cc, op_map.cc, patches/tflite/0001-Add-Customized-NBG-Tflite-Model-Support.patch
=> Add NBG support

CMakeLists.txt, cmake/tflite.cmake, patches/tflite/0001-Add-Customized-NBG-Tflite-Model-Support.patch
=> Update to tensorflow v2.6.0

README.md, patches/tflite/0001-Add-Customized-NBG-Tflite-Model-Support.patch
=> Fixed external delegate not built into benchmark_model/lable_image

CMakeLists.txt, op_map.cc
Added liblog dependency on Android. Fix compliation error.
=> Fixed android build.

.github/workflows/build.gcc.yml
Signed-off-by: ZhangXiang <Xiang.Zhang@verisilicon.com>
=> Add linux-x86-gcc build check

CMakeLists.txt
=> License update for CMakeLists.txt

CMakeLists.txt
=> Add lib64 support for aarch64

CMakeLists.txt, cmake/modules/Findtensorflow.cmake, cmake/modules/Findtim-vx.cmake
=> build tim-vx and tflite as module in cmake

examples/minimal/minimal.cc, op_map.cc, test/models/BatchMatmul.py, test/models/int8BatchMatmul.py
=> map batchmatmul & tflite script

examples/minimal/minimal.cc
=> Fix the crash bug caused by memcpy

test/python/README.md
=> Add readme for pytest

op_map.cc, test/python/dump_model.py, test/python/model_cut.py, test/python/run_model.py, test/python/test_conv2d.py, test/python/utils.py
=> Add model layer dump with python

op_map.cc
=> Add split_v support for yolov4

op_map.cc
=> Mapped Rnn_cell

test/python/utils.py
=> Update golden with Norm_Distributed data

op_map.cc
=> Fix transposeConv2D padding error

op_map.cc
=> Support OneHot, Floor, FloorDiv and Relational ops

test/python/README.md, test/python/test_BatchMatMul.py, test/python/test_conv2d.py, test/python/test_depthwise_conv2d.py
=> Added Depthwise Conv2d pytest

test/python/test_batchmatmul.py, test/python/test_conv2d.py, test/python/test_depthwise_conv2d.py, test/python/utils.py
Reduce depthwise test case size since we want to have a smoking test.
Fix keras package missing in tensorflow module: replace by
tensorflow.python.keras
=> Update test scripts

op_map.cc, test/python/test_conv3d.py
Signed-off-by: Zongwu Yang <zongwu.yang@verisilicon.com>
=> Support Conv3d

cmake/modules/Findtensorflow.cmake
=> Update Tensorflow to v2.8.0

op_map.cc
=> Fix index out of range issue if no bias for fullyconnected

op_map.cc, vx_delegate_adaptor.cc
=> Fix memory issue detected by ASAN

op_map.cc
https://github.com/VeriSilicon/tflite-vx-delegate/issues/62
=> Enable int8 support for PACK

test/python/test_conv1d.py
=> Add pytest for conv1d & grouped conv1d

op_map.cc, test/python/test_dense.py
=> Added pytest for dense

README.md, patches/0001-TensorFlow-V280-Enable-External-Delegate.patch
=> Add doc for enable external_delegate for benchmark_model/lable_image

op_map.cc
=> Fixed reshape bug for inception_v1_224_quant.tflite

op_map.cc
=> Do shape inference for Reshpe to adapt 64bit driver

test/python/test_stack.py
=> test layout inference for stack

test/python/dump_model.py
=> Improve the capacity of model dump

op_map.cc, test/python/test_reverseV2.py
=> Mapped reverseV2

op_map.cc
=> fixed fused activation type error

delegate_main.cc, op_map.cc
=> fixed argmax kernel test & support dynamic shape

op_map.cc
=> Mapped Unpack

op_map.cc
=> Modified unstack param

op_map.cc
=> Fixed pow kernel test

cmake/modules/Findtensorflow.cmake
=> Modify the default tensorflow version to 2.9.0

op_map.cc
=> Fixed pad kernel test

examples/minimal/minimal.cc, op_map.cc
And, minimal is generally used to compare numerical correctness, the get profile code is turned off by default
=> Fixed space_to_batch kernel test

op_map.cc
=> Fixed transpose conv2d kernel test

op_map.cc
=> Fixed conv kernel test

op_map.cc
=> Fixed batch to space kernel test

op_map.cc
=> Fixed dequantization kernel test

op_map.cc
=> Fixed one hot kernel test

op_map.cc
=> Fixed reverse kernel tests

delegate_main.cc, op_map.cc
=> Fiexd reshape kernel test

op_map.cc
=> Fixed reduce kernel test

op_map.cc
=> Fixed squeeze kernel test

op_map.cc
=> Fixed split kernel test

op_map.cc
=> Fixed sub&div kernel test

op_map.cc
=> Fixed expand_dims kernel test

.github/workflows/ci_test.yml, CMakeLists.txt, patches/modified_test.patch, script/KernelTest.sh
=> Added ci kernel test

op_map.cc
=> Fixed LRN kernel test

op_map.cc
=> Fixed strided slice kernel test

op_map.cc
=> Fixed resize kernel test

op_map.cc
=> Fixed maximum&minimum kernel test

test/python/test_grucell.py
=> Added grucell pytest

op_map.cc
=> Fixed conv3d kernel test

delegate_main.cc
=> modified nbg_buf type

op_map.cc
=> replaced directmapop with nativeop

delegate_main.cc, delegate_main.h, op_map.cc
=> Mapped shape operator

.github/workflows/ci_test.yml, CMakeLists.txt, cmake/modules/Findtensorflow.cmake, delegate_main.cc, examples/minimal/CMakeLists.txt, examples/multi_device/CMakeLists.txt, patches/tf_2_10_acc_correction.patch, patches/tf_2_10_kernel_test.patch
update TensorFlow to v2.10.0 
modify ci_test for kerneltest
=> update TensorFlow to v2.10.0 && modify kerneltest ci

examples/minimal/CMakeLists.txt, examples/multi_device/CMakeLists.txt
remove unnecessary link in minimal and multi-device
=> remove wrong links

test/python/test_UnidirectionalSequenceLSTM.py
=> Added pytest case for UnidirectionalSequenceLSTM

delegate_main.cc, op_map.cc
BidirectionalSequenceLSTM mapped without merge output
=> Added BidirectionalLSTM mapping

op_map.cc
Added BidirectionalRnn op and can pass all tflite kerneltest except"EndToEndTest" with tolerance 1e-4
=> Added BidirectionalSequenceRnn mapping

op_map.cc
Added UnidictionalRnn op and can pass tflite kerneltest UnidirectionalRNNOpTest.BlackBoxTest &&
UnidirectionalRNNOpTest.TimeMajorBlackBoxTest with tolerance 1e-4
=> Added UnidirectionalSequenceRnn

op_map.cc, op_status.md
Mapped HashtableLookup op and passed kernel test of this op
=> Mapped HashtableLookup op

op_map.cc, op_status.md
Mapped EmbedddingLookup op && modified op_status.md
=> Mapped EmbeddingLookup op

op_map.cc
Fixed bug of minus axis param of Reversev2
Fixed bug of wrong dim of StridedSlice
Type: Bug Fix
=> Fixed bugs in ReverseV2 and StridedSlice op

op_map.cc
=> Delete argmax/min i8/i32 limit

op_map.cc
=> Refine deconv2d map

op_map.cc
=> Added Cast op support

op_map.cc, test/python/README.md, test/python/conftest.py, test/python/test_attention.py, test/python/utils.py
Remove unreasonable check for batchMatMul
Verified with tensorflow v2.11.0
=> Add TF MultiHeadAttention test model

op_map.cc
Backgraoud: mobilebert_quant model crashed when fc link to a 3-dimensional transpose
Solution: added reshape op after fc if the required output shape is over 2-dimension
Type: Bug Fix
Issue: bugzilla id 33962
=> Fixed bug when fc output is not as required shape

op_map.cc
Fixed bug that elementwise ops not keep the quantize params of the second input
Refine broadcast shape to avoid unnecessary permute around element wise ops
Type: Bug fix
Signed-off-by: Feiyue Chen [Feiyue.Chen@verisilicon.com](mailto:Feiyue.Chen@verisilicon.com)
=> Fixed bug of elementwise ops

delegate_main.cc, delegate_main.h, op_map.cc
Bypass real BroadcastTo Op through key tensor mapping
=> Added BroadcastTo op support

examples/minimal/minimal.cc, examples/util.h
Added int32 data support
Refine mismatch output
Type: Code Improvement
=> Added int32 support for minimal test

op_map.cc
can not support mirror pad and squaredifference tflite operation map mirror pad to pad operation, map squaredifference to sub and pow operation
Type: Code Improve
=> Support mirror_pad and squaredifference operation

op_map.cc
=> Fix MirrorPad pad mode error

op_map.cc
=> Mapped gelu

op_map.cc
=> Added ScatterNd op

op_map.cc
create reverse tensor with wrong attr in gather
Type: bug fix
=> Fixed tensor consume warning

op_map.cc
Rewrite minimum opmapper to bypass this operation if no necessary
=> Refine minimum op

CMakeLists.txt, delegate_main.cc, delegate_main.h, op_map.cc
=> optimization for tiny_yolov4

op_map.cc
Use Reshape operation instead of Broadcast to support optimization in lower levels
Directly set shape to assure the transient output have correct pv
Type: Code Improvement
=> Refine elmentwise op

.github/workflows/ci_test.yml, cmake/modules/Findtensorflow.cmake, patches/tf_2_11_kernel_test.patch
Update TensorFlow fetching
Fixing bugs in building kernel test
=> Update TensorFlow to v2.11.0

test/python/test_attention.py, test/python/test_conv1d.py, test/python/test_conv2d.py, test/python/test_conv3d.py, test/python/test_depthwise_conv2d.py, test/python/test_layout_infer.py, test/python/test_transpose_conv2d.py
Added test script to create layer optimization case for compiler. Fix output quantization issue in legacy test cases.
=> Refine pytest cases

op_map.cc
specifies kernel layout
Type: bug fix
=> fixed bug for convmapper param

op_map.cc
=> fixed yolov4 run issue

delegate_main.cc
Added normalization op fusion
Type: Code Improvement
=> Added opfusion before doing layout inference

op_map.cc
=> fixed quant fc qtype bug

op_map.cc
Rremove restrictions on data types of Pack op
Type: Code Improvement
=> Refine pack mapper

op_map.cc
optimize code for batchmatmul mapper because tim-vx have fixed broadcast param issue
Type: Code Improvement | Documentation
=> Refine batchmatmul mapper

README.md, patches/label_image_support.patch
Added separate patch to enable the external delegate for label_image && Update README.md
Type: Documentation
=> Fixed typing error in README
